# Generated by Django 3.0.4 on 2020-03-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200331_1154'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionUser',
            new_name='UserAnswer',
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'UserAnswers'},
        ),
    ]
