version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api/db.sqlite3:/api/db.sqlite3
    command: >
      sh -c "python api/manage.py wait_for_db && 
             python api/manage.py migrate &&
             python api/manage.py runserver 0.0.0.0:8000"
