version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    image: nginx:alpine
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/api
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - djangonetwork
  api:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: api01
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./api:/api
    links:
      - redis
    networks:
      - djangonetwork
  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: psql01
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork
  redis:
    image: redis:alpine
    container_name: redis01
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
