version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python mind_battle/manage.py wait_for_db && 
             python mind_battle/manage.py migrate &&
             python mind_battle/manage.py runserver 0.0.0.0:8000"
