# Generated by Django 3.0.4 on 2020-03-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionanswer'),
        ('user', '0003_auto_20200316_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuser',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.QuestionAnswer'),
        ),
    ]
