# Generated by Django 3.0.4 on 2020-03-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200321_1219'),
        ('user', '0003_auto_20200321_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.Quiz'),
        ),
    ]
