# Generated by Django 3.0.4 on 2020-03-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionanswer'),
        ('user', '0004_auto_20200316_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuser',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='questionuser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz.QuestionAnswer'),
        ),
    ]
