# Generated by Django 3.0.4 on 2020-03-30 14:13

from django.db import migrations, models
import mind_battle.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200324_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, default='default_quiz.jpeg', null=True, upload_to=mind_battle.helpers.get_quiz_image_location),
        ),
    ]
