# Generated by Django 3.0.4 on 2020-03-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200330_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
