# Generated by Django 3.0.4 on 2020-03-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('good_answer', models.CharField(max_length=255)),
                ('bad_answer_1', models.CharField(max_length=255)),
                ('bad_answer_2', models.CharField(max_length=255)),
                ('bad_answer_3', models.CharField(max_length=255)),
                ('explaination', models.TextField()),
                ('good_answers', models.IntegerField(default=0)),
                ('bad_answers', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
