# Generated by Django 3.0.4 on 2020-03-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bad_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bad_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bad_answer_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='good_answer',
        ),
    ]
