# Generated by Django 3.0.4 on 2020-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200316_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bad_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='good_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
