# Generated by Django 3.0.4 on 2020-03-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200318_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bad_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='good_answers',
        ),
    ]
