# Generated by Django 3.0.4 on 2020-03-21 12:19

from django.db import migrations, models
import mind_battle.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200320_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mind_battle.helpers.get_quiz_image_location),
        ),
    ]
